//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btnhom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHD
    {
        public int idHD { get; set; }
        public int idMH { get; set; }
        public int SoLuong { get; set; }
        public long DonGia { get; set; }
        public Nullable<int> idKM { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual KhuyenMai KhuyenMai { get; set; }
        public virtual MatHang MatHang { get; set; }
    }
}
