//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace btnhom.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatHang()
        {
            this.ChiTietHDs = new HashSet<ChiTietHD>();
            this.KhuyenMais = new HashSet<KhuyenMai>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int SoLuongTon { get; set; }
        public long GiaNhap { get; set; }
        public long GiaBan { get; set; }
        public Nullable<int> idLH { get; set; }
        public string NhaSX { get; set; }
        public string XuatXu { get; set; }
        public string DoTuoi { get; set; }
        public string GhiChu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHD> ChiTietHDs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhuyenMai> KhuyenMais { get; set; }
        public virtual LoaiHang LoaiHang { get; set; }
    }
}
